/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.netology.pyas;

import java.io.IOException;

import ru.netology.pyas.chatprotocol.Protocol;
import ru.netology.pyas.chatprotocol.SimpleProtocol;
import ru.netology.pyas.client.Client;
import ru.netology.pyas.logger.FileLogger;
import ru.netology.pyas.settings.Settings;
import ru.netology.pyas.settings.SettingsReader;

public class ClientApp {

    private final static String SETTINGS_FILE = "settings.txt";

    public static void main(String[] args) {
        Protocol protocol = new SimpleProtocol();
        Settings settings;
        try {
            SettingsReader settingsReader = new SettingsReader(SETTINGS_FILE);
            settings = settingsReader.read();
        } catch (IOException e) {
            System.out.println("Ошибка чтения файла настроек:" + e.getMessage());
            return;
        }

        try (FileLogger logger = new FileLogger(settings.logfile)) {
            new Client(settings.host, settings.port, protocol, logger).run();
        } catch (IOException e) {
            System.out.println("Ошибка открытия файла логов:" + e.getMessage());
        }
    }
}
