/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.netology.pyas;

import ru.netology.pyas.chatprotocol.Protocol;
import ru.netology.pyas.chatprotocol.SimpleProtocol;
import ru.netology.pyas.logger.FileLogger;
import ru.netology.pyas.logger.Logger;
import ru.netology.pyas.server.Server;

public class ServerApp {

    public static void main(String[] args) {
        Protocol protocol = new SimpleProtocol();
        Logger logger = new FileLogger();

        new Server(8080, protocol, logger).run();
    }
}
